name: flutter_tdd_clean_arc_by_resocoder_update
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  mockito: ^5.3.2
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
